/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.ui.tests;

import com.google.inject.Injector;
import edu.project.gamedsl.ui.internal.GamedslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GameDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GamedslActivator.getInstance().getInjector("edu.example.gamedsl.GameDSL");
	}

}
