/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameDSLScopeProvider extends DelegatingScopeProvider {
}
