/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.serializer;

import com.google.inject.Inject;
import edu.example.gamedsl.gameDSL.Board;
import edu.example.gamedsl.gameDSL.CoordinateRange;
import edu.example.gamedsl.gameDSL.GameDSLPackage;
import edu.example.gamedsl.gameDSL.Model;
import edu.example.gamedsl.gameDSL.Move;
import edu.example.gamedsl.gameDSL.Piece;
import edu.example.gamedsl.gameDSL.Placement;
import edu.example.gamedsl.gameDSL.Player;
import edu.example.gamedsl.gameDSL.Rule;
import edu.example.gamedsl.gameDSL.TurnOrder;
import edu.example.gamedsl.gameDSL.WinCondition;
import edu.example.gamedsl.services.GameDSLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class GameDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GameDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GameDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GameDSLPackage.BOARD:
				sequence_Board(context, (Board) semanticObject); 
				return; 
			case GameDSLPackage.COORDINATE_RANGE:
				sequence_CoordinateRange(context, (CoordinateRange) semanticObject); 
				return; 
			case GameDSLPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case GameDSLPackage.MOVE:
				sequence_Move(context, (Move) semanticObject); 
				return; 
			case GameDSLPackage.PIECE:
				sequence_Piece(context, (Piece) semanticObject); 
				return; 
			case GameDSLPackage.PLACEMENT:
				sequence_Placement(context, (Placement) semanticObject); 
				return; 
			case GameDSLPackage.PLAYER:
				sequence_Player(context, (Player) semanticObject); 
				return; 
			case GameDSLPackage.RULE:
				sequence_Rule(context, (Rule) semanticObject); 
				return; 
			case GameDSLPackage.TURN_ORDER:
				sequence_TurnOrder(context, (TurnOrder) semanticObject); 
				return; 
			case GameDSLPackage.WIN_CONDITION:
				sequence_WinCondition(context, (WinCondition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Board
	 *     Board returns Board
	 *
	 * Constraint:
	 *     (rows=INT cols=INT)
	 * </pre>
	 */
	protected void sequence_Board(ISerializationContext context, Board semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.BOARD__ROWS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.BOARD__ROWS));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.BOARD__COLS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.BOARD__COLS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBoardAccess().getRowsINTTerminalRuleCall_1_0(), semanticObject.getRows());
		feeder.accept(grammarAccess.getBoardAccess().getColsINTTerminalRuleCall_3_0(), semanticObject.getCols());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CoordinateRange returns CoordinateRange
	 *
	 * Constraint:
	 *     (startRow=INT startCol=INT endRow=INT endCol=INT)
	 * </pre>
	 */
	protected void sequence_CoordinateRange(ISerializationContext context, CoordinateRange semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__START_ROW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__START_ROW));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__START_COL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__START_COL));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__END_ROW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__END_ROW));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__END_COL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.COORDINATE_RANGE__END_COL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCoordinateRangeAccess().getStartRowINTTerminalRuleCall_1_0(), semanticObject.getStartRow());
		feeder.accept(grammarAccess.getCoordinateRangeAccess().getStartColINTTerminalRuleCall_3_0(), semanticObject.getStartCol());
		feeder.accept(grammarAccess.getCoordinateRangeAccess().getEndRowINTTerminalRuleCall_7_0(), semanticObject.getEndRow());
		feeder.accept(grammarAccess.getCoordinateRangeAccess().getEndColINTTerminalRuleCall_9_0(), semanticObject.getEndCol());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     statements+=Statement+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Move
	 *     Move returns Move
	 *
	 * Constraint:
	 *     (piece=[Piece|ID] direction=STRING steps=INT condition=STRING?)
	 * </pre>
	 */
	protected void sequence_Move(ISerializationContext context, Move semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Piece
	 *     Piece returns Piece
	 *
	 * Constraint:
	 *     (name=STRING symbol=STRING owner=STRING count=INT?)
	 * </pre>
	 */
	protected void sequence_Piece(ISerializationContext context, Piece semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Placement
	 *     Placement returns Placement
	 *
	 * Constraint:
	 *     (piece=[Piece|ID] range=CoordinateRange owner=STRING)
	 * </pre>
	 */
	protected void sequence_Placement(ISerializationContext context, Placement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.PLACEMENT__PIECE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.PLACEMENT__PIECE));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.PLACEMENT__RANGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.PLACEMENT__RANGE));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.PLACEMENT__OWNER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.PLACEMENT__OWNER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPlacementAccess().getPiecePieceIDTerminalRuleCall_1_0_1(), semanticObject.eGet(GameDSLPackage.Literals.PLACEMENT__PIECE, false));
		feeder.accept(grammarAccess.getPlacementAccess().getRangeCoordinateRangeParserRuleCall_3_0(), semanticObject.getRange());
		feeder.accept(grammarAccess.getPlacementAccess().getOwnerSTRINGTerminalRuleCall_5_0(), semanticObject.getOwner());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Player
	 *     Player returns Player
	 *
	 * Constraint:
	 *     name=STRING
	 * </pre>
	 */
	protected void sequence_Player(ISerializationContext context, Player semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.PLAYER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.PLAYER__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPlayerAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Rule
	 *     Rule returns Rule
	 *
	 * Constraint:
	 *     (name=STRING condition=STRING action=STRING)
	 * </pre>
	 */
	protected void sequence_Rule(ISerializationContext context, Rule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.RULE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.RULE__NAME));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.RULE__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.RULE__CONDITION));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.RULE__ACTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.RULE__ACTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRuleAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRuleAccess().getConditionSTRINGTerminalRuleCall_3_0(), semanticObject.getCondition());
		feeder.accept(grammarAccess.getRuleAccess().getActionSTRINGTerminalRuleCall_5_0(), semanticObject.getAction());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns TurnOrder
	 *     TurnOrder returns TurnOrder
	 *
	 * Constraint:
	 *     (players+=STRING players+=STRING*)
	 * </pre>
	 */
	protected void sequence_TurnOrder(ISerializationContext context, TurnOrder semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns WinCondition
	 *     WinCondition returns WinCondition
	 *
	 * Constraint:
	 *     (condition=STRING winner=STRING)
	 * </pre>
	 */
	protected void sequence_WinCondition(ISerializationContext context, WinCondition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.WIN_CONDITION__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.WIN_CONDITION__CONDITION));
			if (transientValues.isValueTransient(semanticObject, GameDSLPackage.Literals.WIN_CONDITION__WINNER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GameDSLPackage.Literals.WIN_CONDITION__WINNER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWinConditionAccess().getConditionSTRINGTerminalRuleCall_2_0(), semanticObject.getCondition());
		feeder.accept(grammarAccess.getWinConditionAccess().getWinnerSTRINGTerminalRuleCall_6_0(), semanticObject.getWinner());
		feeder.finish();
	}
	
	
}
