/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.example.gamedsl.GameDSLRuntimeModule;
import edu.example.gamedsl.GameDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GameDSLIdeSetup extends GameDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GameDSLRuntimeModule(), new GameDSLIdeModule()));
	}
	
}
