/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.ui;

import com.google.inject.Injector;
import edu.project.gamedsl.ui.internal.GamedslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GamedslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GamedslActivator activator = GamedslActivator.getInstance();
		return activator != null ? activator.getInjector(GamedslActivator.EDU_EXAMPLE_GAMEDSL_GAMEDSL) : null;
	}

}
