/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGameDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.example.gamedsl.gameDSL.GameDSLPackage.eINSTANCE);
		return result;
	}
}
