/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GameDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Model");
		private final Assignment cStatementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStatementsStatementParserRuleCall_0 = (RuleCall)cStatementsAssignment.eContents().get(0);
		
		//Model:
		//    statements+=Statement*;
		@Override public ParserRule getRule() { return rule; }
		
		//statements+=Statement*
		public Assignment getStatementsAssignment() { return cStatementsAssignment; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_0() { return cStatementsStatementParserRuleCall_0; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBoardParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPlayerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTurnOrderParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cPieceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPlacementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cMoveParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cRuleParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cWinConditionParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Statement:
		//    Board | Player | TurnOrder | Piece | Placement | Move | Rule | WinCondition;
		@Override public ParserRule getRule() { return rule; }
		
		//Board | Player | TurnOrder | Piece | Placement | Move | Rule | WinCondition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Board
		public RuleCall getBoardParserRuleCall_0() { return cBoardParserRuleCall_0; }
		
		//Player
		public RuleCall getPlayerParserRuleCall_1() { return cPlayerParserRuleCall_1; }
		
		//TurnOrder
		public RuleCall getTurnOrderParserRuleCall_2() { return cTurnOrderParserRuleCall_2; }
		
		//Piece
		public RuleCall getPieceParserRuleCall_3() { return cPieceParserRuleCall_3; }
		
		//Placement
		public RuleCall getPlacementParserRuleCall_4() { return cPlacementParserRuleCall_4; }
		
		//Move
		public RuleCall getMoveParserRuleCall_5() { return cMoveParserRuleCall_5; }
		
		//Rule
		public RuleCall getRuleParserRuleCall_6() { return cRuleParserRuleCall_6; }
		
		//WinCondition
		public RuleCall getWinConditionParserRuleCall_7() { return cWinConditionParserRuleCall_7; }
	}
	public class BoardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Board");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBoardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRowsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRowsINTTerminalRuleCall_1_0 = (RuleCall)cRowsAssignment_1.eContents().get(0);
		private final Keyword cXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColsINTTerminalRuleCall_3_0 = (RuleCall)cColsAssignment_3.eContents().get(0);
		
		//Board:
		//    'board' rows=INT 'x' cols=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'board' rows=INT 'x' cols=INT
		public Group getGroup() { return cGroup; }
		
		//'board'
		public Keyword getBoardKeyword_0() { return cBoardKeyword_0; }
		
		//rows=INT
		public Assignment getRowsAssignment_1() { return cRowsAssignment_1; }
		
		//INT
		public RuleCall getRowsINTTerminalRuleCall_1_0() { return cRowsINTTerminalRuleCall_1_0; }
		
		//'x'
		public Keyword getXKeyword_2() { return cXKeyword_2; }
		
		//cols=INT
		public Assignment getColsAssignment_3() { return cColsAssignment_3; }
		
		//INT
		public RuleCall getColsINTTerminalRuleCall_3_0() { return cColsINTTerminalRuleCall_3_0; }
	}
	public class PlayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Player");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlayerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Player:
		//    'player' name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'player' name=STRING
		public Group getGroup() { return cGroup; }
		
		//'player'
		public Keyword getPlayerKeyword_0() { return cPlayerKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	public class TurnOrderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.TurnOrder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTurn_orderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPlayersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPlayersSTRINGTerminalRuleCall_2_0 = (RuleCall)cPlayersAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPlayersAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPlayersSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cPlayersAssignment_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TurnOrder:
		//    'turn_order' '[' players+=STRING (',' players+=STRING)* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'turn_order' '[' players+=STRING (',' players+=STRING)* ']'
		public Group getGroup() { return cGroup; }
		
		//'turn_order'
		public Keyword getTurn_orderKeyword_0() { return cTurn_orderKeyword_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//players+=STRING
		public Assignment getPlayersAssignment_2() { return cPlayersAssignment_2; }
		
		//STRING
		public RuleCall getPlayersSTRINGTerminalRuleCall_2_0() { return cPlayersSTRINGTerminalRuleCall_2_0; }
		
		//(',' players+=STRING)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//players+=STRING
		public Assignment getPlayersAssignment_3_1() { return cPlayersAssignment_3_1; }
		
		//STRING
		public RuleCall getPlayersSTRINGTerminalRuleCall_3_1_0() { return cPlayersSTRINGTerminalRuleCall_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}
	public class PieceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Piece");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPieceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSymbolKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSymbolAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSymbolSTRINGTerminalRuleCall_3_0 = (RuleCall)cSymbolAssignment_3.eContents().get(0);
		private final Keyword cOwnerKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOwnerAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOwnerSTRINGTerminalRuleCall_5_0 = (RuleCall)cOwnerAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cXKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCountAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCountINTTerminalRuleCall_6_1_0 = (RuleCall)cCountAssignment_6_1.eContents().get(0);
		
		//Piece:
		//    'piece' name=STRING 'symbol' symbol=STRING 'owner' owner=STRING ('x' count=INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'piece' name=STRING 'symbol' symbol=STRING 'owner' owner=STRING ('x' count=INT)?
		public Group getGroup() { return cGroup; }
		
		//'piece'
		public Keyword getPieceKeyword_0() { return cPieceKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'symbol'
		public Keyword getSymbolKeyword_2() { return cSymbolKeyword_2; }
		
		//symbol=STRING
		public Assignment getSymbolAssignment_3() { return cSymbolAssignment_3; }
		
		//STRING
		public RuleCall getSymbolSTRINGTerminalRuleCall_3_0() { return cSymbolSTRINGTerminalRuleCall_3_0; }
		
		//'owner'
		public Keyword getOwnerKeyword_4() { return cOwnerKeyword_4; }
		
		//owner=STRING
		public Assignment getOwnerAssignment_5() { return cOwnerAssignment_5; }
		
		//STRING
		public RuleCall getOwnerSTRINGTerminalRuleCall_5_0() { return cOwnerSTRINGTerminalRuleCall_5_0; }
		
		//('x' count=INT)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'x'
		public Keyword getXKeyword_6_0() { return cXKeyword_6_0; }
		
		//count=INT
		public Assignment getCountAssignment_6_1() { return cCountAssignment_6_1; }
		
		//INT
		public RuleCall getCountINTTerminalRuleCall_6_1_0() { return cCountINTTerminalRuleCall_6_1_0; }
	}
	public class PlacementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Placement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPieceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cPiecePieceCrossReference_1_0 = (CrossReference)cPieceAssignment_1.eContents().get(0);
		private final RuleCall cPiecePieceIDTerminalRuleCall_1_0_1 = (RuleCall)cPiecePieceCrossReference_1_0.eContents().get(1);
		private final Keyword cAtKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRangeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRangeCoordinateRangeParserRuleCall_3_0 = (RuleCall)cRangeAssignment_3.eContents().get(0);
		private final Keyword cForKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOwnerAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOwnerSTRINGTerminalRuleCall_5_0 = (RuleCall)cOwnerAssignment_5.eContents().get(0);
		
		//Placement:
		//    'place' piece=[Piece] 'at' range=CoordinateRange 'for' owner=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'place' piece=[Piece] 'at' range=CoordinateRange 'for' owner=STRING
		public Group getGroup() { return cGroup; }
		
		//'place'
		public Keyword getPlaceKeyword_0() { return cPlaceKeyword_0; }
		
		//piece=[Piece]
		public Assignment getPieceAssignment_1() { return cPieceAssignment_1; }
		
		//[Piece]
		public CrossReference getPiecePieceCrossReference_1_0() { return cPiecePieceCrossReference_1_0; }
		
		//ID
		public RuleCall getPiecePieceIDTerminalRuleCall_1_0_1() { return cPiecePieceIDTerminalRuleCall_1_0_1; }
		
		//'at'
		public Keyword getAtKeyword_2() { return cAtKeyword_2; }
		
		//range=CoordinateRange
		public Assignment getRangeAssignment_3() { return cRangeAssignment_3; }
		
		//CoordinateRange
		public RuleCall getRangeCoordinateRangeParserRuleCall_3_0() { return cRangeCoordinateRangeParserRuleCall_3_0; }
		
		//'for'
		public Keyword getForKeyword_4() { return cForKeyword_4; }
		
		//owner=STRING
		public Assignment getOwnerAssignment_5() { return cOwnerAssignment_5; }
		
		//STRING
		public RuleCall getOwnerSTRINGTerminalRuleCall_5_0() { return cOwnerSTRINGTerminalRuleCall_5_0; }
	}
	public class MoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Move");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMoveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPieceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cPiecePieceCrossReference_1_0 = (CrossReference)cPieceAssignment_1.eContents().get(0);
		private final RuleCall cPiecePieceIDTerminalRuleCall_1_0_1 = (RuleCall)cPiecePieceCrossReference_1_0.eContents().get(1);
		private final Keyword cDirectionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDirectionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDirectionSTRINGTerminalRuleCall_3_0 = (RuleCall)cDirectionAssignment_3.eContents().get(0);
		private final Assignment cStepsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStepsINTTerminalRuleCall_4_0 = (RuleCall)cStepsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIfKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cConditionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cConditionSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cConditionAssignment_5_1.eContents().get(0);
		
		//Move:
		//    'move' piece=[Piece] 'direction' direction=STRING steps=INT ('if' condition=STRING)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'move' piece=[Piece] 'direction' direction=STRING steps=INT ('if' condition=STRING)?
		public Group getGroup() { return cGroup; }
		
		//'move'
		public Keyword getMoveKeyword_0() { return cMoveKeyword_0; }
		
		//piece=[Piece]
		public Assignment getPieceAssignment_1() { return cPieceAssignment_1; }
		
		//[Piece]
		public CrossReference getPiecePieceCrossReference_1_0() { return cPiecePieceCrossReference_1_0; }
		
		//ID
		public RuleCall getPiecePieceIDTerminalRuleCall_1_0_1() { return cPiecePieceIDTerminalRuleCall_1_0_1; }
		
		//'direction'
		public Keyword getDirectionKeyword_2() { return cDirectionKeyword_2; }
		
		//direction=STRING
		public Assignment getDirectionAssignment_3() { return cDirectionAssignment_3; }
		
		//STRING
		public RuleCall getDirectionSTRINGTerminalRuleCall_3_0() { return cDirectionSTRINGTerminalRuleCall_3_0; }
		
		//steps=INT
		public Assignment getStepsAssignment_4() { return cStepsAssignment_4; }
		
		//INT
		public RuleCall getStepsINTTerminalRuleCall_4_0() { return cStepsINTTerminalRuleCall_4_0; }
		
		//('if' condition=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'if'
		public Keyword getIfKeyword_5_0() { return cIfKeyword_5_0; }
		
		//condition=STRING
		public Assignment getConditionAssignment_5_1() { return cConditionAssignment_5_1; }
		
		//STRING
		public RuleCall getConditionSTRINGTerminalRuleCall_5_1_0() { return cConditionSTRINGTerminalRuleCall_5_1_0; }
	}
	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cIfKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionSTRINGTerminalRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cThenKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cActionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cActionSTRINGTerminalRuleCall_5_0 = (RuleCall)cActionAssignment_5.eContents().get(0);
		
		//Rule:
		//    'rule' name=STRING 'if' condition=STRING 'then' action=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'rule' name=STRING 'if' condition=STRING 'then' action=STRING
		public Group getGroup() { return cGroup; }
		
		//'rule'
		public Keyword getRuleKeyword_0() { return cRuleKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'if'
		public Keyword getIfKeyword_2() { return cIfKeyword_2; }
		
		//condition=STRING
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//STRING
		public RuleCall getConditionSTRINGTerminalRuleCall_3_0() { return cConditionSTRINGTerminalRuleCall_3_0; }
		
		//'then'
		public Keyword getThenKeyword_4() { return cThenKeyword_4; }
		
		//action=STRING
		public Assignment getActionAssignment_5() { return cActionAssignment_5; }
		
		//STRING
		public RuleCall getActionSTRINGTerminalRuleCall_5_0() { return cActionSTRINGTerminalRuleCall_5_0; }
	}
	public class WinConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.WinCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWin_conditionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cIfKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionSTRINGTerminalRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final Keyword cThenKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cWinnerKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cWinnerAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cWinnerSTRINGTerminalRuleCall_6_0 = (RuleCall)cWinnerAssignment_6.eContents().get(0);
		
		//WinCondition:
		//    'win_condition' 'if' condition=STRING 'then' 'winner' '=' winner=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'win_condition' 'if' condition=STRING 'then' 'winner' '=' winner=STRING
		public Group getGroup() { return cGroup; }
		
		//'win_condition'
		public Keyword getWin_conditionKeyword_0() { return cWin_conditionKeyword_0; }
		
		//'if'
		public Keyword getIfKeyword_1() { return cIfKeyword_1; }
		
		//condition=STRING
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }
		
		//STRING
		public RuleCall getConditionSTRINGTerminalRuleCall_2_0() { return cConditionSTRINGTerminalRuleCall_2_0; }
		
		//'then'
		public Keyword getThenKeyword_3() { return cThenKeyword_3; }
		
		//'winner'
		public Keyword getWinnerKeyword_4() { return cWinnerKeyword_4; }
		
		//'='
		public Keyword getEqualsSignKeyword_5() { return cEqualsSignKeyword_5; }
		
		//winner=STRING
		public Assignment getWinnerAssignment_6() { return cWinnerAssignment_6; }
		
		//STRING
		public RuleCall getWinnerSTRINGTerminalRuleCall_6_0() { return cWinnerSTRINGTerminalRuleCall_6_0; }
	}
	public class CoordinateRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.example.gamedsl.GameDSL.CoordinateRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStartRowAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStartRowINTTerminalRuleCall_1_0 = (RuleCall)cStartRowAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cStartColAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStartColINTTerminalRuleCall_3_0 = (RuleCall)cStartColAssignment_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cHyphenMinusKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEndRowAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cEndRowINTTerminalRuleCall_7_0 = (RuleCall)cEndRowAssignment_7.eContents().get(0);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cEndColAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cEndColINTTerminalRuleCall_9_0 = (RuleCall)cEndColAssignment_9.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//CoordinateRange:
		//    '[' startRow=INT ',' startCol=INT ']' '-' '[' endRow=INT ',' endCol=INT ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'[' startRow=INT ',' startCol=INT ']' '-' '[' endRow=INT ',' endCol=INT ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//startRow=INT
		public Assignment getStartRowAssignment_1() { return cStartRowAssignment_1; }
		
		//INT
		public RuleCall getStartRowINTTerminalRuleCall_1_0() { return cStartRowINTTerminalRuleCall_1_0; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//startCol=INT
		public Assignment getStartColAssignment_3() { return cStartColAssignment_3; }
		
		//INT
		public RuleCall getStartColINTTerminalRuleCall_3_0() { return cStartColINTTerminalRuleCall_3_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_5() { return cHyphenMinusKeyword_5; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6() { return cLeftSquareBracketKeyword_6; }
		
		//endRow=INT
		public Assignment getEndRowAssignment_7() { return cEndRowAssignment_7; }
		
		//INT
		public RuleCall getEndRowINTTerminalRuleCall_7_0() { return cEndRowINTTerminalRuleCall_7_0; }
		
		//','
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//endCol=INT
		public Assignment getEndColAssignment_9() { return cEndColAssignment_9; }
		
		//INT
		public RuleCall getEndColINTTerminalRuleCall_9_0() { return cEndColINTTerminalRuleCall_9_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	
	
	private final ModelElements pModel;
	private final StatementElements pStatement;
	private final BoardElements pBoard;
	private final PlayerElements pPlayer;
	private final TurnOrderElements pTurnOrder;
	private final PieceElements pPiece;
	private final PlacementElements pPlacement;
	private final MoveElements pMove;
	private final RuleElements pRule;
	private final WinConditionElements pWinCondition;
	private final CoordinateRangeElements pCoordinateRange;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GameDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pStatement = new StatementElements();
		this.pBoard = new BoardElements();
		this.pPlayer = new PlayerElements();
		this.pTurnOrder = new TurnOrderElements();
		this.pPiece = new PieceElements();
		this.pPlacement = new PlacementElements();
		this.pMove = new MoveElements();
		this.pRule = new RuleElements();
		this.pWinCondition = new WinConditionElements();
		this.pCoordinateRange = new CoordinateRangeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("edu.example.gamedsl.GameDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    statements+=Statement*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Statement:
	//    Board | Player | TurnOrder | Piece | Placement | Move | Rule | WinCondition;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Board:
	//    'board' rows=INT 'x' cols=INT;
	public BoardElements getBoardAccess() {
		return pBoard;
	}
	
	public ParserRule getBoardRule() {
		return getBoardAccess().getRule();
	}
	
	//Player:
	//    'player' name=STRING;
	public PlayerElements getPlayerAccess() {
		return pPlayer;
	}
	
	public ParserRule getPlayerRule() {
		return getPlayerAccess().getRule();
	}
	
	//TurnOrder:
	//    'turn_order' '[' players+=STRING (',' players+=STRING)* ']';
	public TurnOrderElements getTurnOrderAccess() {
		return pTurnOrder;
	}
	
	public ParserRule getTurnOrderRule() {
		return getTurnOrderAccess().getRule();
	}
	
	//Piece:
	//    'piece' name=STRING 'symbol' symbol=STRING 'owner' owner=STRING ('x' count=INT)?;
	public PieceElements getPieceAccess() {
		return pPiece;
	}
	
	public ParserRule getPieceRule() {
		return getPieceAccess().getRule();
	}
	
	//Placement:
	//    'place' piece=[Piece] 'at' range=CoordinateRange 'for' owner=STRING;
	public PlacementElements getPlacementAccess() {
		return pPlacement;
	}
	
	public ParserRule getPlacementRule() {
		return getPlacementAccess().getRule();
	}
	
	//Move:
	//    'move' piece=[Piece] 'direction' direction=STRING steps=INT ('if' condition=STRING)?;
	public MoveElements getMoveAccess() {
		return pMove;
	}
	
	public ParserRule getMoveRule() {
		return getMoveAccess().getRule();
	}
	
	//Rule:
	//    'rule' name=STRING 'if' condition=STRING 'then' action=STRING;
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}
	
	//WinCondition:
	//    'win_condition' 'if' condition=STRING 'then' 'winner' '=' winner=STRING;
	public WinConditionElements getWinConditionAccess() {
		return pWinCondition;
	}
	
	public ParserRule getWinConditionRule() {
		return getWinConditionAccess().getRule();
	}
	
	//CoordinateRange:
	//    '[' startRow=INT ',' startCol=INT ']' '-' '[' endRow=INT ',' endCol=INT ']';
	public CoordinateRangeElements getCoordinateRangeAccess() {
		return pCoordinateRange;
	}
	
	public ParserRule getCoordinateRangeRule() {
		return getCoordinateRangeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
