/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GameDSLUiModule extends AbstractGameDSLUiModule {

	public GameDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
