/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Board</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.Board#getRows <em>Rows</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Board#getCols <em>Cols</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getBoard()
 * @model
 * @generated
 */
public interface Board extends Statement
{
  /**
   * Returns the value of the '<em><b>Rows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rows</em>' attribute.
   * @see #setRows(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getBoard_Rows()
   * @model
   * @generated
   */
  int getRows();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Board#getRows <em>Rows</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rows</em>' attribute.
   * @see #getRows()
   * @generated
   */
  void setRows(int value);

  /**
   * Returns the value of the '<em><b>Cols</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cols</em>' attribute.
   * @see #setCols(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getBoard_Cols()
   * @model
   * @generated
   */
  int getCols();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Board#getCols <em>Cols</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cols</em>' attribute.
   * @see #getCols()
   * @generated
   */
  void setCols(int value);

} // Board
