/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Coordinate Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.CoordinateRange#getStartRow <em>Start Row</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.CoordinateRange#getStartCol <em>Start Col</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.CoordinateRange#getEndRow <em>End Row</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.CoordinateRange#getEndCol <em>End Col</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getCoordinateRange()
 * @model
 * @generated
 */
public interface CoordinateRange extends EObject
{
  /**
   * Returns the value of the '<em><b>Start Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Row</em>' attribute.
   * @see #setStartRow(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getCoordinateRange_StartRow()
   * @model
   * @generated
   */
  int getStartRow();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getStartRow <em>Start Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Row</em>' attribute.
   * @see #getStartRow()
   * @generated
   */
  void setStartRow(int value);

  /**
   * Returns the value of the '<em><b>Start Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Col</em>' attribute.
   * @see #setStartCol(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getCoordinateRange_StartCol()
   * @model
   * @generated
   */
  int getStartCol();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getStartCol <em>Start Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Col</em>' attribute.
   * @see #getStartCol()
   * @generated
   */
  void setStartCol(int value);

  /**
   * Returns the value of the '<em><b>End Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Row</em>' attribute.
   * @see #setEndRow(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getCoordinateRange_EndRow()
   * @model
   * @generated
   */
  int getEndRow();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getEndRow <em>End Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Row</em>' attribute.
   * @see #getEndRow()
   * @generated
   */
  void setEndRow(int value);

  /**
   * Returns the value of the '<em><b>End Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Col</em>' attribute.
   * @see #setEndCol(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getCoordinateRange_EndCol()
   * @model
   * @generated
   */
  int getEndCol();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getEndCol <em>End Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Col</em>' attribute.
   * @see #getEndCol()
   * @generated
   */
  void setEndCol(int value);

} // CoordinateRange
