/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.example.gamedsl.gameDSL.GameDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GameDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gameDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.edu/gamedsl/GameDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gameDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameDSLPackage eINSTANCE = edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.ModelImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.StatementImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.BoardImpl <em>Board</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.BoardImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getBoard()
   * @generated
   */
  int BOARD = 2;

  /**
   * The feature id for the '<em><b>Rows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__ROWS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cols</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__COLS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Board</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.PlayerImpl <em>Player</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.PlayerImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getPlayer()
   * @generated
   */
  int PLAYER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYER__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Player</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYER_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.TurnOrderImpl <em>Turn Order</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.TurnOrderImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getTurnOrder()
   * @generated
   */
  int TURN_ORDER = 4;

  /**
   * The feature id for the '<em><b>Players</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_ORDER__PLAYERS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Turn Order</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_ORDER_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.PieceImpl <em>Piece</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.PieceImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getPiece()
   * @generated
   */
  int PIECE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIECE__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIECE__SYMBOL = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Owner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIECE__OWNER = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIECE__COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Piece</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIECE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.PlacementImpl <em>Placement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.PlacementImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getPlacement()
   * @generated
   */
  int PLACEMENT = 6;

  /**
   * The feature id for the '<em><b>Piece</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACEMENT__PIECE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACEMENT__RANGE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Owner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACEMENT__OWNER = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Placement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.MoveImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getMove()
   * @generated
   */
  int MOVE = 7;

  /**
   * The feature id for the '<em><b>Piece</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__PIECE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__DIRECTION = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Steps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__STEPS = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__CONDITION = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.RuleImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getRule()
   * @generated
   */
  int RULE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITION = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACTION = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.WinConditionImpl <em>Win Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.WinConditionImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getWinCondition()
   * @generated
   */
  int WIN_CONDITION = 9;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIN_CONDITION__CONDITION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Winner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIN_CONDITION__WINNER = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Win Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WIN_CONDITION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl <em>Coordinate Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl
   * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getCoordinateRange()
   * @generated
   */
  int COORDINATE_RANGE = 10;

  /**
   * The feature id for the '<em><b>Start Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_RANGE__START_ROW = 0;

  /**
   * The feature id for the '<em><b>Start Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_RANGE__START_COL = 1;

  /**
   * The feature id for the '<em><b>End Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_RANGE__END_ROW = 2;

  /**
   * The feature id for the '<em><b>End Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_RANGE__END_COL = 3;

  /**
   * The number of structural features of the '<em>Coordinate Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATE_RANGE_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see edu.example.gamedsl.gameDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link edu.example.gamedsl.gameDSL.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see edu.example.gamedsl.gameDSL.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see edu.example.gamedsl.gameDSL.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Board <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Board</em>'.
   * @see edu.example.gamedsl.gameDSL.Board
   * @generated
   */
  EClass getBoard();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Board#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rows</em>'.
   * @see edu.example.gamedsl.gameDSL.Board#getRows()
   * @see #getBoard()
   * @generated
   */
  EAttribute getBoard_Rows();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Board#getCols <em>Cols</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cols</em>'.
   * @see edu.example.gamedsl.gameDSL.Board#getCols()
   * @see #getBoard()
   * @generated
   */
  EAttribute getBoard_Cols();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Player <em>Player</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Player</em>'.
   * @see edu.example.gamedsl.gameDSL.Player
   * @generated
   */
  EClass getPlayer();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Player#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.example.gamedsl.gameDSL.Player#getName()
   * @see #getPlayer()
   * @generated
   */
  EAttribute getPlayer_Name();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.TurnOrder <em>Turn Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn Order</em>'.
   * @see edu.example.gamedsl.gameDSL.TurnOrder
   * @generated
   */
  EClass getTurnOrder();

  /**
   * Returns the meta object for the attribute list '{@link edu.example.gamedsl.gameDSL.TurnOrder#getPlayers <em>Players</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Players</em>'.
   * @see edu.example.gamedsl.gameDSL.TurnOrder#getPlayers()
   * @see #getTurnOrder()
   * @generated
   */
  EAttribute getTurnOrder_Players();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Piece <em>Piece</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Piece</em>'.
   * @see edu.example.gamedsl.gameDSL.Piece
   * @generated
   */
  EClass getPiece();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Piece#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.example.gamedsl.gameDSL.Piece#getName()
   * @see #getPiece()
   * @generated
   */
  EAttribute getPiece_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Piece#getSymbol <em>Symbol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Symbol</em>'.
   * @see edu.example.gamedsl.gameDSL.Piece#getSymbol()
   * @see #getPiece()
   * @generated
   */
  EAttribute getPiece_Symbol();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Piece#getOwner <em>Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owner</em>'.
   * @see edu.example.gamedsl.gameDSL.Piece#getOwner()
   * @see #getPiece()
   * @generated
   */
  EAttribute getPiece_Owner();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Piece#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count</em>'.
   * @see edu.example.gamedsl.gameDSL.Piece#getCount()
   * @see #getPiece()
   * @generated
   */
  EAttribute getPiece_Count();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Placement <em>Placement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Placement</em>'.
   * @see edu.example.gamedsl.gameDSL.Placement
   * @generated
   */
  EClass getPlacement();

  /**
   * Returns the meta object for the reference '{@link edu.example.gamedsl.gameDSL.Placement#getPiece <em>Piece</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Piece</em>'.
   * @see edu.example.gamedsl.gameDSL.Placement#getPiece()
   * @see #getPlacement()
   * @generated
   */
  EReference getPlacement_Piece();

  /**
   * Returns the meta object for the containment reference '{@link edu.example.gamedsl.gameDSL.Placement#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see edu.example.gamedsl.gameDSL.Placement#getRange()
   * @see #getPlacement()
   * @generated
   */
  EReference getPlacement_Range();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Placement#getOwner <em>Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owner</em>'.
   * @see edu.example.gamedsl.gameDSL.Placement#getOwner()
   * @see #getPlacement()
   * @generated
   */
  EAttribute getPlacement_Owner();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see edu.example.gamedsl.gameDSL.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the reference '{@link edu.example.gamedsl.gameDSL.Move#getPiece <em>Piece</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Piece</em>'.
   * @see edu.example.gamedsl.gameDSL.Move#getPiece()
   * @see #getMove()
   * @generated
   */
  EReference getMove_Piece();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Move#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see edu.example.gamedsl.gameDSL.Move#getDirection()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Direction();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Move#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Steps</em>'.
   * @see edu.example.gamedsl.gameDSL.Move#getSteps()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Steps();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Move#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see edu.example.gamedsl.gameDSL.Move#getCondition()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Condition();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see edu.example.gamedsl.gameDSL.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.example.gamedsl.gameDSL.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Rule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see edu.example.gamedsl.gameDSL.Rule#getCondition()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Condition();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.Rule#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see edu.example.gamedsl.gameDSL.Rule#getAction()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Action();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.WinCondition <em>Win Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Win Condition</em>'.
   * @see edu.example.gamedsl.gameDSL.WinCondition
   * @generated
   */
  EClass getWinCondition();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.WinCondition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see edu.example.gamedsl.gameDSL.WinCondition#getCondition()
   * @see #getWinCondition()
   * @generated
   */
  EAttribute getWinCondition_Condition();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.WinCondition#getWinner <em>Winner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Winner</em>'.
   * @see edu.example.gamedsl.gameDSL.WinCondition#getWinner()
   * @see #getWinCondition()
   * @generated
   */
  EAttribute getWinCondition_Winner();

  /**
   * Returns the meta object for class '{@link edu.example.gamedsl.gameDSL.CoordinateRange <em>Coordinate Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinate Range</em>'.
   * @see edu.example.gamedsl.gameDSL.CoordinateRange
   * @generated
   */
  EClass getCoordinateRange();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getStartRow <em>Start Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Row</em>'.
   * @see edu.example.gamedsl.gameDSL.CoordinateRange#getStartRow()
   * @see #getCoordinateRange()
   * @generated
   */
  EAttribute getCoordinateRange_StartRow();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getStartCol <em>Start Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Col</em>'.
   * @see edu.example.gamedsl.gameDSL.CoordinateRange#getStartCol()
   * @see #getCoordinateRange()
   * @generated
   */
  EAttribute getCoordinateRange_StartCol();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getEndRow <em>End Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Row</em>'.
   * @see edu.example.gamedsl.gameDSL.CoordinateRange#getEndRow()
   * @see #getCoordinateRange()
   * @generated
   */
  EAttribute getCoordinateRange_EndRow();

  /**
   * Returns the meta object for the attribute '{@link edu.example.gamedsl.gameDSL.CoordinateRange#getEndCol <em>End Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Col</em>'.
   * @see edu.example.gamedsl.gameDSL.CoordinateRange#getEndCol()
   * @see #getCoordinateRange()
   * @generated
   */
  EAttribute getCoordinateRange_EndCol();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameDSLFactory getGameDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.ModelImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.StatementImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.BoardImpl <em>Board</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.BoardImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getBoard()
     * @generated
     */
    EClass BOARD = eINSTANCE.getBoard();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOARD__ROWS = eINSTANCE.getBoard_Rows();

    /**
     * The meta object literal for the '<em><b>Cols</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOARD__COLS = eINSTANCE.getBoard_Cols();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.PlayerImpl <em>Player</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.PlayerImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getPlayer()
     * @generated
     */
    EClass PLAYER = eINSTANCE.getPlayer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLAYER__NAME = eINSTANCE.getPlayer_Name();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.TurnOrderImpl <em>Turn Order</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.TurnOrderImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getTurnOrder()
     * @generated
     */
    EClass TURN_ORDER = eINSTANCE.getTurnOrder();

    /**
     * The meta object literal for the '<em><b>Players</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_ORDER__PLAYERS = eINSTANCE.getTurnOrder_Players();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.PieceImpl <em>Piece</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.PieceImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getPiece()
     * @generated
     */
    EClass PIECE = eINSTANCE.getPiece();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIECE__NAME = eINSTANCE.getPiece_Name();

    /**
     * The meta object literal for the '<em><b>Symbol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIECE__SYMBOL = eINSTANCE.getPiece_Symbol();

    /**
     * The meta object literal for the '<em><b>Owner</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIECE__OWNER = eINSTANCE.getPiece_Owner();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIECE__COUNT = eINSTANCE.getPiece_Count();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.PlacementImpl <em>Placement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.PlacementImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getPlacement()
     * @generated
     */
    EClass PLACEMENT = eINSTANCE.getPlacement();

    /**
     * The meta object literal for the '<em><b>Piece</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLACEMENT__PIECE = eINSTANCE.getPlacement_Piece();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLACEMENT__RANGE = eINSTANCE.getPlacement_Range();

    /**
     * The meta object literal for the '<em><b>Owner</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLACEMENT__OWNER = eINSTANCE.getPlacement_Owner();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.MoveImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Piece</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE__PIECE = eINSTANCE.getMove_Piece();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__DIRECTION = eINSTANCE.getMove_Direction();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__STEPS = eINSTANCE.getMove_Steps();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__CONDITION = eINSTANCE.getMove_Condition();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.RuleImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__CONDITION = eINSTANCE.getRule_Condition();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__ACTION = eINSTANCE.getRule_Action();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.WinConditionImpl <em>Win Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.WinConditionImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getWinCondition()
     * @generated
     */
    EClass WIN_CONDITION = eINSTANCE.getWinCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIN_CONDITION__CONDITION = eINSTANCE.getWinCondition_Condition();

    /**
     * The meta object literal for the '<em><b>Winner</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WIN_CONDITION__WINNER = eINSTANCE.getWinCondition_Winner();

    /**
     * The meta object literal for the '{@link edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl <em>Coordinate Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl
     * @see edu.example.gamedsl.gameDSL.impl.GameDSLPackageImpl#getCoordinateRange()
     * @generated
     */
    EClass COORDINATE_RANGE = eINSTANCE.getCoordinateRange();

    /**
     * The meta object literal for the '<em><b>Start Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE_RANGE__START_ROW = eINSTANCE.getCoordinateRange_StartRow();

    /**
     * The meta object literal for the '<em><b>Start Col</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE_RANGE__START_COL = eINSTANCE.getCoordinateRange_StartCol();

    /**
     * The meta object literal for the '<em><b>End Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE_RANGE__END_ROW = eINSTANCE.getCoordinateRange_EndRow();

    /**
     * The meta object literal for the '<em><b>End Col</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATE_RANGE__END_COL = eINSTANCE.getCoordinateRange_EndCol();

  }

} //GameDSLPackage
