/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.Move#getPiece <em>Piece</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Move#getDirection <em>Direction</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Move#getSteps <em>Steps</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Move#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends Statement
{
  /**
   * Returns the value of the '<em><b>Piece</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piece</em>' reference.
   * @see #setPiece(Piece)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getMove_Piece()
   * @model
   * @generated
   */
  Piece getPiece();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Move#getPiece <em>Piece</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Piece</em>' reference.
   * @see #getPiece()
   * @generated
   */
  void setPiece(Piece value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see #setDirection(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getMove_Direction()
   * @model
   * @generated
   */
  String getDirection();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Move#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see #getDirection()
   * @generated
   */
  void setDirection(String value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' attribute.
   * @see #setSteps(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getMove_Steps()
   * @model
   * @generated
   */
  int getSteps();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Move#getSteps <em>Steps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Steps</em>' attribute.
   * @see #getSteps()
   * @generated
   */
  void setSteps(int value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getMove_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Move#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

} // Move
