/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Piece</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.Piece#getName <em>Name</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Piece#getSymbol <em>Symbol</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Piece#getOwner <em>Owner</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Piece#getCount <em>Count</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPiece()
 * @model
 * @generated
 */
public interface Piece extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPiece_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Piece#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol</em>' attribute.
   * @see #setSymbol(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPiece_Symbol()
   * @model
   * @generated
   */
  String getSymbol();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Piece#getSymbol <em>Symbol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol</em>' attribute.
   * @see #getSymbol()
   * @generated
   */
  void setSymbol(String value);

  /**
   * Returns the value of the '<em><b>Owner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owner</em>' attribute.
   * @see #setOwner(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPiece_Owner()
   * @model
   * @generated
   */
  String getOwner();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Piece#getOwner <em>Owner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owner</em>' attribute.
   * @see #getOwner()
   * @generated
   */
  void setOwner(String value);

  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(int)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPiece_Count()
   * @model
   * @generated
   */
  int getCount();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Piece#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  void setCount(int value);

} // Piece
