/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Placement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.Placement#getPiece <em>Piece</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Placement#getRange <em>Range</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Placement#getOwner <em>Owner</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPlacement()
 * @model
 * @generated
 */
public interface Placement extends Statement
{
  /**
   * Returns the value of the '<em><b>Piece</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piece</em>' reference.
   * @see #setPiece(Piece)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPlacement_Piece()
   * @model
   * @generated
   */
  Piece getPiece();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Placement#getPiece <em>Piece</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Piece</em>' reference.
   * @see #getPiece()
   * @generated
   */
  void setPiece(Piece value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(CoordinateRange)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPlacement_Range()
   * @model containment="true"
   * @generated
   */
  CoordinateRange getRange();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Placement#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(CoordinateRange value);

  /**
   * Returns the value of the '<em><b>Owner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owner</em>' attribute.
   * @see #setOwner(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getPlacement_Owner()
   * @model
   * @generated
   */
  String getOwner();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Placement#getOwner <em>Owner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owner</em>' attribute.
   * @see #getOwner()
   * @generated
   */
  void setOwner(String value);

} // Placement
