/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.Rule#getName <em>Name</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Rule#getCondition <em>Condition</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.Rule#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getRule_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Rule#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getRule_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.Rule#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

} // Rule
