/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
