/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turn Order</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.TurnOrder#getPlayers <em>Players</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getTurnOrder()
 * @model
 * @generated
 */
public interface TurnOrder extends Statement
{
  /**
   * Returns the value of the '<em><b>Players</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Players</em>' attribute list.
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getTurnOrder_Players()
   * @model unique="false"
   * @generated
   */
  EList<String> getPlayers();

} // TurnOrder
