/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Win Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.WinCondition#getCondition <em>Condition</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.WinCondition#getWinner <em>Winner</em>}</li>
 * </ul>
 *
 * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getWinCondition()
 * @model
 * @generated
 */
public interface WinCondition extends Statement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getWinCondition_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.WinCondition#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Winner</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Winner</em>' attribute.
   * @see #setWinner(String)
   * @see edu.example.gamedsl.gameDSL.GameDSLPackage#getWinCondition_Winner()
   * @model
   * @generated
   */
  String getWinner();

  /**
   * Sets the value of the '{@link edu.example.gamedsl.gameDSL.WinCondition#getWinner <em>Winner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Winner</em>' attribute.
   * @see #getWinner()
   * @generated
   */
  void setWinner(String value);

} // WinCondition
