/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import edu.example.gamedsl.ide.contentassist.antlr.internal.InternalGameDSLParser;
import edu.example.gamedsl.services.GameDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GameDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GameDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GameDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getBoardAccess().getGroup(), "rule__Board__Group__0");
			builder.put(grammarAccess.getPlayerAccess().getGroup(), "rule__Player__Group__0");
			builder.put(grammarAccess.getTurnOrderAccess().getGroup(), "rule__TurnOrder__Group__0");
			builder.put(grammarAccess.getTurnOrderAccess().getGroup_3(), "rule__TurnOrder__Group_3__0");
			builder.put(grammarAccess.getPieceAccess().getGroup(), "rule__Piece__Group__0");
			builder.put(grammarAccess.getPieceAccess().getGroup_6(), "rule__Piece__Group_6__0");
			builder.put(grammarAccess.getPlacementAccess().getGroup(), "rule__Placement__Group__0");
			builder.put(grammarAccess.getMoveAccess().getGroup(), "rule__Move__Group__0");
			builder.put(grammarAccess.getMoveAccess().getGroup_5(), "rule__Move__Group_5__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getWinConditionAccess().getGroup(), "rule__WinCondition__Group__0");
			builder.put(grammarAccess.getCoordinateRangeAccess().getGroup(), "rule__CoordinateRange__Group__0");
			builder.put(grammarAccess.getModelAccess().getStatementsAssignment(), "rule__Model__StatementsAssignment");
			builder.put(grammarAccess.getBoardAccess().getRowsAssignment_1(), "rule__Board__RowsAssignment_1");
			builder.put(grammarAccess.getBoardAccess().getColsAssignment_3(), "rule__Board__ColsAssignment_3");
			builder.put(grammarAccess.getPlayerAccess().getNameAssignment_1(), "rule__Player__NameAssignment_1");
			builder.put(grammarAccess.getTurnOrderAccess().getPlayersAssignment_2(), "rule__TurnOrder__PlayersAssignment_2");
			builder.put(grammarAccess.getTurnOrderAccess().getPlayersAssignment_3_1(), "rule__TurnOrder__PlayersAssignment_3_1");
			builder.put(grammarAccess.getPieceAccess().getNameAssignment_1(), "rule__Piece__NameAssignment_1");
			builder.put(grammarAccess.getPieceAccess().getSymbolAssignment_3(), "rule__Piece__SymbolAssignment_3");
			builder.put(grammarAccess.getPieceAccess().getOwnerAssignment_5(), "rule__Piece__OwnerAssignment_5");
			builder.put(grammarAccess.getPieceAccess().getCountAssignment_6_1(), "rule__Piece__CountAssignment_6_1");
			builder.put(grammarAccess.getPlacementAccess().getPieceAssignment_1(), "rule__Placement__PieceAssignment_1");
			builder.put(grammarAccess.getPlacementAccess().getRangeAssignment_3(), "rule__Placement__RangeAssignment_3");
			builder.put(grammarAccess.getPlacementAccess().getOwnerAssignment_5(), "rule__Placement__OwnerAssignment_5");
			builder.put(grammarAccess.getMoveAccess().getPieceAssignment_1(), "rule__Move__PieceAssignment_1");
			builder.put(grammarAccess.getMoveAccess().getDirectionAssignment_3(), "rule__Move__DirectionAssignment_3");
			builder.put(grammarAccess.getMoveAccess().getStepsAssignment_4(), "rule__Move__StepsAssignment_4");
			builder.put(grammarAccess.getMoveAccess().getConditionAssignment_5_1(), "rule__Move__ConditionAssignment_5_1");
			builder.put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getConditionAssignment_3(), "rule__Rule__ConditionAssignment_3");
			builder.put(grammarAccess.getRuleAccess().getActionAssignment_5(), "rule__Rule__ActionAssignment_5");
			builder.put(grammarAccess.getWinConditionAccess().getConditionAssignment_2(), "rule__WinCondition__ConditionAssignment_2");
			builder.put(grammarAccess.getWinConditionAccess().getWinnerAssignment_6(), "rule__WinCondition__WinnerAssignment_6");
			builder.put(grammarAccess.getCoordinateRangeAccess().getStartRowAssignment_1(), "rule__CoordinateRange__StartRowAssignment_1");
			builder.put(grammarAccess.getCoordinateRangeAccess().getStartColAssignment_3(), "rule__CoordinateRange__StartColAssignment_3");
			builder.put(grammarAccess.getCoordinateRangeAccess().getEndRowAssignment_7(), "rule__CoordinateRange__EndRowAssignment_7");
			builder.put(grammarAccess.getCoordinateRangeAccess().getEndColAssignment_9(), "rule__CoordinateRange__EndColAssignment_9");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GameDSLGrammarAccess grammarAccess;

	@Override
	protected InternalGameDSLParser createParser() {
		InternalGameDSLParser result = new InternalGameDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
