/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL.impl;

import edu.example.gamedsl.gameDSL.CoordinateRange;
import edu.example.gamedsl.gameDSL.GameDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Coordinate Range</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl#getStartRow <em>Start Row</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl#getStartCol <em>Start Col</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl#getEndRow <em>End Row</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.CoordinateRangeImpl#getEndCol <em>End Col</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CoordinateRangeImpl extends MinimalEObjectImpl.Container implements CoordinateRange
{
  /**
   * The default value of the '{@link #getStartRow() <em>Start Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartRow()
   * @generated
   * @ordered
   */
  protected static final int START_ROW_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStartRow() <em>Start Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartRow()
   * @generated
   * @ordered
   */
  protected int startRow = START_ROW_EDEFAULT;

  /**
   * The default value of the '{@link #getStartCol() <em>Start Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartCol()
   * @generated
   * @ordered
   */
  protected static final int START_COL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStartCol() <em>Start Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartCol()
   * @generated
   * @ordered
   */
  protected int startCol = START_COL_EDEFAULT;

  /**
   * The default value of the '{@link #getEndRow() <em>End Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndRow()
   * @generated
   * @ordered
   */
  protected static final int END_ROW_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getEndRow() <em>End Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndRow()
   * @generated
   * @ordered
   */
  protected int endRow = END_ROW_EDEFAULT;

  /**
   * The default value of the '{@link #getEndCol() <em>End Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndCol()
   * @generated
   * @ordered
   */
  protected static final int END_COL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getEndCol() <em>End Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndCol()
   * @generated
   * @ordered
   */
  protected int endCol = END_COL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CoordinateRangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GameDSLPackage.Literals.COORDINATE_RANGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getStartRow()
  {
    return startRow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStartRow(int newStartRow)
  {
    int oldStartRow = startRow;
    startRow = newStartRow;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.COORDINATE_RANGE__START_ROW, oldStartRow, startRow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getStartCol()
  {
    return startCol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStartCol(int newStartCol)
  {
    int oldStartCol = startCol;
    startCol = newStartCol;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.COORDINATE_RANGE__START_COL, oldStartCol, startCol));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getEndRow()
  {
    return endRow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEndRow(int newEndRow)
  {
    int oldEndRow = endRow;
    endRow = newEndRow;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.COORDINATE_RANGE__END_ROW, oldEndRow, endRow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getEndCol()
  {
    return endCol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEndCol(int newEndCol)
  {
    int oldEndCol = endCol;
    endCol = newEndCol;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.COORDINATE_RANGE__END_COL, oldEndCol, endCol));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GameDSLPackage.COORDINATE_RANGE__START_ROW:
        return getStartRow();
      case GameDSLPackage.COORDINATE_RANGE__START_COL:
        return getStartCol();
      case GameDSLPackage.COORDINATE_RANGE__END_ROW:
        return getEndRow();
      case GameDSLPackage.COORDINATE_RANGE__END_COL:
        return getEndCol();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GameDSLPackage.COORDINATE_RANGE__START_ROW:
        setStartRow((Integer)newValue);
        return;
      case GameDSLPackage.COORDINATE_RANGE__START_COL:
        setStartCol((Integer)newValue);
        return;
      case GameDSLPackage.COORDINATE_RANGE__END_ROW:
        setEndRow((Integer)newValue);
        return;
      case GameDSLPackage.COORDINATE_RANGE__END_COL:
        setEndCol((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GameDSLPackage.COORDINATE_RANGE__START_ROW:
        setStartRow(START_ROW_EDEFAULT);
        return;
      case GameDSLPackage.COORDINATE_RANGE__START_COL:
        setStartCol(START_COL_EDEFAULT);
        return;
      case GameDSLPackage.COORDINATE_RANGE__END_ROW:
        setEndRow(END_ROW_EDEFAULT);
        return;
      case GameDSLPackage.COORDINATE_RANGE__END_COL:
        setEndCol(END_COL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GameDSLPackage.COORDINATE_RANGE__START_ROW:
        return startRow != START_ROW_EDEFAULT;
      case GameDSLPackage.COORDINATE_RANGE__START_COL:
        return startCol != START_COL_EDEFAULT;
      case GameDSLPackage.COORDINATE_RANGE__END_ROW:
        return endRow != END_ROW_EDEFAULT;
      case GameDSLPackage.COORDINATE_RANGE__END_COL:
        return endCol != END_COL_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (startRow: ");
    result.append(startRow);
    result.append(", startCol: ");
    result.append(startCol);
    result.append(", endRow: ");
    result.append(endRow);
    result.append(", endCol: ");
    result.append(endCol);
    result.append(')');
    return result.toString();
  }

} //CoordinateRangeImpl
