/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL.impl;

import edu.example.gamedsl.gameDSL.GameDSLPackage;
import edu.example.gamedsl.gameDSL.Move;
import edu.example.gamedsl.gameDSL.Piece;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.MoveImpl#getPiece <em>Piece</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.MoveImpl#getDirection <em>Direction</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.MoveImpl#getSteps <em>Steps</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.MoveImpl#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MoveImpl extends StatementImpl implements Move
{
  /**
   * The cached value of the '{@link #getPiece() <em>Piece</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPiece()
   * @generated
   * @ordered
   */
  protected Piece piece;

  /**
   * The default value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected static final String DIRECTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected String direction = DIRECTION_EDEFAULT;

  /**
   * The default value of the '{@link #getSteps() <em>Steps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSteps()
   * @generated
   * @ordered
   */
  protected static final int STEPS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSteps() <em>Steps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSteps()
   * @generated
   * @ordered
   */
  protected int steps = STEPS_EDEFAULT;

  /**
   * The default value of the '{@link #getCondition() <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition()
   * @generated
   * @ordered
   */
  protected static final String CONDITION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCondition() <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition()
   * @generated
   * @ordered
   */
  protected String condition = CONDITION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GameDSLPackage.Literals.MOVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Piece getPiece()
  {
    if (piece != null && piece.eIsProxy())
    {
      InternalEObject oldPiece = (InternalEObject)piece;
      piece = (Piece)eResolveProxy(oldPiece);
      if (piece != oldPiece)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GameDSLPackage.MOVE__PIECE, oldPiece, piece));
      }
    }
    return piece;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Piece basicGetPiece()
  {
    return piece;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPiece(Piece newPiece)
  {
    Piece oldPiece = piece;
    piece = newPiece;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.MOVE__PIECE, oldPiece, piece));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDirection()
  {
    return direction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDirection(String newDirection)
  {
    String oldDirection = direction;
    direction = newDirection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.MOVE__DIRECTION, oldDirection, direction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSteps()
  {
    return steps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSteps(int newSteps)
  {
    int oldSteps = steps;
    steps = newSteps;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.MOVE__STEPS, oldSteps, steps));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCondition()
  {
    return condition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCondition(String newCondition)
  {
    String oldCondition = condition;
    condition = newCondition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.MOVE__CONDITION, oldCondition, condition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GameDSLPackage.MOVE__PIECE:
        if (resolve) return getPiece();
        return basicGetPiece();
      case GameDSLPackage.MOVE__DIRECTION:
        return getDirection();
      case GameDSLPackage.MOVE__STEPS:
        return getSteps();
      case GameDSLPackage.MOVE__CONDITION:
        return getCondition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GameDSLPackage.MOVE__PIECE:
        setPiece((Piece)newValue);
        return;
      case GameDSLPackage.MOVE__DIRECTION:
        setDirection((String)newValue);
        return;
      case GameDSLPackage.MOVE__STEPS:
        setSteps((Integer)newValue);
        return;
      case GameDSLPackage.MOVE__CONDITION:
        setCondition((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GameDSLPackage.MOVE__PIECE:
        setPiece((Piece)null);
        return;
      case GameDSLPackage.MOVE__DIRECTION:
        setDirection(DIRECTION_EDEFAULT);
        return;
      case GameDSLPackage.MOVE__STEPS:
        setSteps(STEPS_EDEFAULT);
        return;
      case GameDSLPackage.MOVE__CONDITION:
        setCondition(CONDITION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GameDSLPackage.MOVE__PIECE:
        return piece != null;
      case GameDSLPackage.MOVE__DIRECTION:
        return DIRECTION_EDEFAULT == null ? direction != null : !DIRECTION_EDEFAULT.equals(direction);
      case GameDSLPackage.MOVE__STEPS:
        return steps != STEPS_EDEFAULT;
      case GameDSLPackage.MOVE__CONDITION:
        return CONDITION_EDEFAULT == null ? condition != null : !CONDITION_EDEFAULT.equals(condition);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (direction: ");
    result.append(direction);
    result.append(", steps: ");
    result.append(steps);
    result.append(", condition: ");
    result.append(condition);
    result.append(')');
    return result.toString();
  }

} //MoveImpl
