/**
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl.gameDSL.impl;

import edu.example.gamedsl.gameDSL.CoordinateRange;
import edu.example.gamedsl.gameDSL.GameDSLPackage;
import edu.example.gamedsl.gameDSL.Piece;
import edu.example.gamedsl.gameDSL.Placement;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Placement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.PlacementImpl#getPiece <em>Piece</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.PlacementImpl#getRange <em>Range</em>}</li>
 *   <li>{@link edu.example.gamedsl.gameDSL.impl.PlacementImpl#getOwner <em>Owner</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PlacementImpl extends StatementImpl implements Placement
{
  /**
   * The cached value of the '{@link #getPiece() <em>Piece</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPiece()
   * @generated
   * @ordered
   */
  protected Piece piece;

  /**
   * The cached value of the '{@link #getRange() <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRange()
   * @generated
   * @ordered
   */
  protected CoordinateRange range;

  /**
   * The default value of the '{@link #getOwner() <em>Owner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwner()
   * @generated
   * @ordered
   */
  protected static final String OWNER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOwner() <em>Owner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwner()
   * @generated
   * @ordered
   */
  protected String owner = OWNER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlacementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GameDSLPackage.Literals.PLACEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Piece getPiece()
  {
    if (piece != null && piece.eIsProxy())
    {
      InternalEObject oldPiece = (InternalEObject)piece;
      piece = (Piece)eResolveProxy(oldPiece);
      if (piece != oldPiece)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GameDSLPackage.PLACEMENT__PIECE, oldPiece, piece));
      }
    }
    return piece;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Piece basicGetPiece()
  {
    return piece;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPiece(Piece newPiece)
  {
    Piece oldPiece = piece;
    piece = newPiece;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.PLACEMENT__PIECE, oldPiece, piece));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CoordinateRange getRange()
  {
    return range;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRange(CoordinateRange newRange, NotificationChain msgs)
  {
    CoordinateRange oldRange = range;
    range = newRange;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GameDSLPackage.PLACEMENT__RANGE, oldRange, newRange);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRange(CoordinateRange newRange)
  {
    if (newRange != range)
    {
      NotificationChain msgs = null;
      if (range != null)
        msgs = ((InternalEObject)range).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GameDSLPackage.PLACEMENT__RANGE, null, msgs);
      if (newRange != null)
        msgs = ((InternalEObject)newRange).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GameDSLPackage.PLACEMENT__RANGE, null, msgs);
      msgs = basicSetRange(newRange, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.PLACEMENT__RANGE, newRange, newRange));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOwner()
  {
    return owner;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOwner(String newOwner)
  {
    String oldOwner = owner;
    owner = newOwner;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameDSLPackage.PLACEMENT__OWNER, oldOwner, owner));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GameDSLPackage.PLACEMENT__RANGE:
        return basicSetRange(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GameDSLPackage.PLACEMENT__PIECE:
        if (resolve) return getPiece();
        return basicGetPiece();
      case GameDSLPackage.PLACEMENT__RANGE:
        return getRange();
      case GameDSLPackage.PLACEMENT__OWNER:
        return getOwner();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GameDSLPackage.PLACEMENT__PIECE:
        setPiece((Piece)newValue);
        return;
      case GameDSLPackage.PLACEMENT__RANGE:
        setRange((CoordinateRange)newValue);
        return;
      case GameDSLPackage.PLACEMENT__OWNER:
        setOwner((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GameDSLPackage.PLACEMENT__PIECE:
        setPiece((Piece)null);
        return;
      case GameDSLPackage.PLACEMENT__RANGE:
        setRange((CoordinateRange)null);
        return;
      case GameDSLPackage.PLACEMENT__OWNER:
        setOwner(OWNER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GameDSLPackage.PLACEMENT__PIECE:
        return piece != null;
      case GameDSLPackage.PLACEMENT__RANGE:
        return range != null;
      case GameDSLPackage.PLACEMENT__OWNER:
        return OWNER_EDEFAULT == null ? owner != null : !OWNER_EDEFAULT.equals(owner);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (owner: ");
    result.append(owner);
    result.append(')');
    return result.toString();
  }

} //PlacementImpl
