/*
 * generated by Xtext 2.38.0
 */
package edu.example.gamedsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GameDSLStandaloneSetup extends GameDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new GameDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
